###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/658a26ce89eeef86c9590399

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Teste Usuário",
  "email": "teste@teste.com",
  "password": "123456",
  "cpf": "44444444444",
  "phone": "11999999999"
}

###
DELETE http://localhost:3000/users/658a2831d4a6250a700796c4